### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\lsaa-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C7%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709072245535984-16%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\32nb-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C8%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709082322160457-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TfT3qktOD9hLzStYplBK4VPjQNsasNluA6giKWTI3o8%3D&st=2017-09-08T23%3A17%3A39Z&se=2017-09-09T23%3A27%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\4c34-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C13%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709132208262443-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KDolbgo2qwV2YAGpFtuuwrEPFJU0PbI7AekWqXSeL3c%3D&st=2017-09-13T22%3A04%3A03Z&se=2017-09-14T22%3A14%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ltza-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C14%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709142247307104-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VJqcSN1QB9w2p5oISq53xSADtc3uTTU9MPFjhecpggA%3D&st=2017-09-14T22%3A43%3A09Z&se=2017-09-15T22%3A53%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\sdna-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C15%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709152314415566-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wH8meOCrkRZ70ZRib%2FaFUu80anwgCuH5dJxtQZSlf9U%3D&st=2017-09-15T23%3A10%3A00Z&se=2017-09-16T23%3A20%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\olrx-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C18%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709182217172693-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M28Dso2DSbgnQr5hey62pKgeTNuHxzj3dGXsplAH5uI%3D&st=2017-09-18T22%3A12%3A39Z&se=2017-09-19T22%3A22%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\223h-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709192212343556-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Gu2jhVpvygxXI0xbRkYdE0DH9mWOm3qTXiWl9ZVFPzo%3D&st=2017-09-19T22%3A07%3A53Z&se=2017-09-20T22%3A17%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\stp1-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C20%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709202207524030-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FaVih0h%2FYZHNxX1cyOc5vOypyTRHP%2BUdioiS5%2BRXrgs%3D&st=2017-09-20T22%3A04%3A42Z&se=2017-09-21T22%3A14%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\4gof-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C21%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709212205105116-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=P7YggxckRxjiTNxfAcMJTKlkaXrt%2FzsjqN5wLRz0VAA%3D&st=2017-09-21T22%3A00%3A30Z&se=2017-09-22T22%3A10%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\btay-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709222204330473-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gc6Mwd1Ewn9B%2BNEF1g3in2YC%2FEk3aJ6ZU9cbi56lgMQ%3D&st=2017-09-22T21%3A59%3A49Z&se=2017-09-23T22%3A09%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\zjev-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C24%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709240156545302-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nCX8esyOY95LM2mOvpR%2BLyiQhRl0JbbuuVUJyKePELY%3D&st=2017-09-24T01%3A52%3A25Z&se=2017-09-25T02%3A02%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\m15c-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C25%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709252210333888-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KALUoiDL1Z%2FbzfF6EyCs1e4%2Fit9UKNW4B27jm%2FG6ZhA%3D&st=2017-09-25T22%3A06%3A27Z&se=2017-09-26T22%3A16%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\jj0r-s, target branch: live, target branch commit: 53cd5d2767765b2b5f3e79b7878be984bc38e5cb, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C26%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709262213397594-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=s4FLNRiDL2cMfIwPCTqj3hHtIEr8%2BG1ZEG9v5OZUobE%3D&st=2017-09-26T22%3A10%3A57Z&se=2017-10-27T22%3A15%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
