### PR TITLE
pr real time: same base 2

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[82983a8](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/82983a86ff52c0b8ef50c4df8961326f80d267ea)_: 

:clock10: **Full build**: the average full build time is _7 min(s) 29 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[82983a8](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/82983a86ff52c0b8ef50c4df8961326f80d267ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/azure-cli-configuration.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/yajun-source2/docs-ref-conceptual/azure-cli-configuration.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-latest&branch=pr-en-us-1100) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1100) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-1100) (azure-cli-2018-03-01-hybrid) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C202006100731351362-1100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JY5csxbqiAGaR9smylfx6Qw%2FkobuAM63u1hKLDj2X74%3D&st=2020-06-10T07%3A50%3A45Z&se=2020-07-11T07%3A55%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/195583c8-b16e-8120-c0f7-89fb2f60ce66?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[82983a8](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/82983a86ff52c0b8ef50c4df8961326f80d267ea)_: 

:clock10: **Full build**: the average full build time is _7 min(s) 32 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[82983a8](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/82983a86ff52c0b8ef50c4df8961326f80d267ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/azure-cli-configuration.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/yajun-source2/docs-ref-conceptual/azure-cli-configuration.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-latest&branch=pr-en-us-1100) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1100) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-configuration?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-1100) (azure-cli-2018-03-01-hybrid) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C6%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C202006100829365924-1100%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tWDVSj7GUk3IERZSDdzOuo5Xnrqvr4INmj%2BYuRDM2U0%3D&st=2020-06-10T08%3A39%3A06Z&se=2020-07-11T08%3A44%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/195583c8-b16e-8120-c0f7-89fb2f60ce66?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
