### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\odye-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C29%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201709292205202243-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yqi2%2FIJB57e6Da%2FawWCFdDL3pZO27OKdJ8rKDITBdGQ%3D&st=2017-09-29T22%3A00%3A33Z&se=2017-10-30T22%3A05%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\tdkp-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710022247448654-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hDKgX6laFQCui8cZUO6WVazwA8HbtWUBAnjPJ3TC%2FS8%3D&st=2017-10-02T22%3A43%3A21Z&se=2017-11-02T22%3A48%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\45tk-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C3%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710032235040061-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LUqBc%2BSguirs%2B0idgrWUvIJAUWoovdHR4q7%2B5OjXYno%3D&st=2017-10-03T22%3A30%3A38Z&se=2017-11-03T22%3A35%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pypu-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C4%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710042236103092-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GRO7RIVDOSmD1Ks44RHGVcxPd714Omy%2F9ZWv%2BusW0Uw%3D&st=2017-10-04T22%3A31%3A28Z&se=2017-11-04T22%3A36%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\5jge-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710052235338058-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QaDwUdOnw%2F9Kia8TEbVi%2FmnzPVrJR%2Fy7BA%2B5uyGeJQA%3D&st=2017-10-05T22%3A30%3A54Z&se=2017-11-05T22%3A35%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\e23v-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C6%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710062305342212-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BjwOqjsFR%2BrtpBOuFloRbRZyW48zv51WHPzY%2F2jX7tg%3D&st=2017-10-06T23%3A01%3A19Z&se=2017-11-06T23%3A06%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\wuyj-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C9%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710092305385001-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uknWHf4OZ2DGw4FkgxpQmhJbYUP%2BoaW32I2VNKHN6%2FQ%3D&st=2017-10-09T23%3A02%3A23Z&se=2017-11-09T23%3A07%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\my23-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710102221004407-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5s%2BfHjsw%2FRz9HIRQ9E%2BYCy%2FvOPxH4qDOR%2B2znPbRDYQ%3D&st=2017-10-10T22%3A16%3A11Z&se=2017-11-10T22%3A21%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\2bm0-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C11%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710112246230453-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7YyMOLnMnnJZDlqRW%2BICTvX5bi7JgfWyCLNuwf1ZDSI%3D&st=2017-10-11T22%3A41%3A34Z&se=2017-11-11T22%3A46%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\eo1e-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C12%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710122204404214-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=avFEjDDeLiWGZE5bCTQNrevsZ%2BIWkOmUJOs%2BANmDP2s%3D&st=2017-10-12T21%3A59%3A51Z&se=2017-11-12T22%3A04%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\idoz-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C13%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710132206153036-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Gu%2FKKjQp9JVPd0AZC%2FYDIw5ie2PbdP2sT7lb%2FIUx%2F%2FA%3D&st=2017-10-13T22%3A01%3A43Z&se=2017-11-13T22%3A06%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\domt-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C16%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710162241578339-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L8ys%2FQ5w%2FhlAfgyR51%2BgYckLZtRUpt2MRLmwTu6A8SY%3D&st=2017-10-16T22%3A37%3A10Z&se=2017-11-16T22%3A42%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\t5hu-s, target branch: live, target branch commit: 1cf5037423bd38fd85359a871162ff0db4085567, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C10%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201710172314126681-18%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=22EbeURiBOkS8y10tun3ddIYrvde5fpQOmlQ3bK4j%2Bs%3D&st=2017-10-17T23%3A09%3A34Z&se=2017-11-17T23%3A14%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
