### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ytr2-s, target branch: live, target branch commit: 966e7a9d7fcbdf2152efcd4e33a3d7c6660ba830, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C3%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201803232206528599-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2p5TkzeoNSmlR%2FDL%2FLlJZOWQyDHaMho%2BNFAjmfE9zcw%3D&st=2018-03-23T22%3A02%3A07Z&se=2018-04-23T22%3A07%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pf1z-s, target branch: live, target branch commit: 966e7a9d7fcbdf2152efcd4e33a3d7c6660ba830, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C3%5C26%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201803262204274864-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3f%2BzUeJFdkt9XWUNlW8cTETlEwkirv4FRHaTYnjg6%2FE%3D&st=2018-03-26T21%3A59%3A42Z&se=2018-04-26T22%3A04%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pqii-s, target branch: live, target branch commit: 966e7a9d7fcbdf2152efcd4e33a3d7c6660ba830, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C3%5C28%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201803280011130151-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qM%2FIjO96Uo6aTHo9fMU8g6co6uaeSXlx4IbTmcOdApo%3D&st=2018-03-28T00%3A06%3A31Z&se=2018-04-28T00%3A11%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\prmz-s, target branch: live, target branch commit: 966e7a9d7fcbdf2152efcd4e33a3d7c6660ba830, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C3%5C29%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201803292207496173-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FUq4twStqTpG%2Fv71KzllIe3%2Fkd1qS2OrHfrH2fHp%2Fg8%3D&st=2018-03-29T22%3A03%3A04Z&se=2018-04-29T22%3A08%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\l34n-s, target branch: live, target branch commit: 966e7a9d7fcbdf2152efcd4e33a3d7c6660ba830, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C4%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201804022204268489-27%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t8otK8uVZ5Bm7sYYizmUNn8HXSwo%2Bj82YwwBSqbFCOo%3D&st=2018-04-02T21%3A59%3A42Z&se=2018-05-03T22%3A04%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
