### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ldnj-s, target branch: live, target branch commit: d13f6f0f98fcedd49aff5c4e4e0995cb444938c8, source branch: live-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C9%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810092134427794-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ku%2FC36m3HaTzejaxfduQuyE7LF5PfxJR8LFkpOwcBHI%3D&st=2018-10-09T21%3A29%3A57Z&se=2018-11-09T21%3A34%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ojbe-s, target branch: live, target branch commit: d13f6f0f98fcedd49aff5c4e4e0995cb444938c8, source branch: live-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C9%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810092216213654-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GgkZ4GMYMb1bZJu0uaPWyOLfpDoTaPLAKSa7SOrdcKg%3D&st=2018-10-09T22%3A11%3A40Z&se=2018-11-09T22%3A16%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\jw3i-s, target branch: live, target branch commit: d13f6f0f98fcedd49aff5c4e4e0995cb444938c8, source branch: live-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810102213157413-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nJA%2BL5MyETW2J5Wox6nmI7VByPnUtarqtaaGrPDWAqM%3D&st=2018-10-10T22%3A08%3A33Z&se=2018-11-10T22%3A13%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitattributes](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/.gitattributes) | :white_check_mark:Succeeded | |
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/TOC.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/vm/image?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/app.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/app?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app/owner.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/app/owner.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/app/owner?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/group.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group/member.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/group/member.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/group/member?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/sp.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/sp?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp/credential.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/sp/credential.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/sp/credential?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp/owner.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/sp/owner.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/sp/owner?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/user.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ad/user.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ad/user?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/botservice/bot.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ext/botservice/bot.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ext/botservice/bot?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/botservice/index.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ext/botservice/index.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ext/botservice/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/dms-preview/dms/project/task.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/ext/dms-preview/dms/project/task.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ext/dms-preview/dms/project/task?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/hdinsight.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/hdinsight.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/hdinsight?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/keyvault.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/keyvault?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/storage.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/keyvault/storage.yml) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/keyvault/storage/sas-definition.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/keyvault/storage/sas-definition.yml) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/network.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/address-pool.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/address-pool.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/address-pool?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/auth-cert.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/auth-cert.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/auth-cert?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-ip.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-ip.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/frontend-ip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-port.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-port.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/frontend-port?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-listener.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-listener.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/http-listener?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-settings.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-settings.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/http-settings?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/probe.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/probe.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/probe?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/rule.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/rule.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/rule?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/ssl-cert.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/ssl-cert.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/ssl-cert?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/ssl-policy.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/ssl-policy.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/ssl-policy?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/url-path-map.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/url-path-map.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/url-path-map?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/url-path-map/rule.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/url-path-map/rule.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/url-path-map/rule?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/waf-config.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/application-gateway/waf-config.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/application-gateway/waf-config?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/a.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/a.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/a?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/aaaa.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/aaaa.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/aaaa?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/cname.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/cname.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/cname?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/mx.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/mx.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/mx?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/ns.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/ns.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/ns?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/ptr.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/ptr.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/ptr?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/soa.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/soa.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/soa?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/srv.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/srv.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/srv?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/record-set/txt.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/record-set/txt.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/record-set/txt?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/dns/zone.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/dns/zone.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/dns/zone?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/express-route.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/express-route.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/express-route?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/express-route/peering.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/express-route/peering.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/express-route/peering?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/express-route/peering/connection.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/express-route/peering/connection.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/express-route/peering/connection?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/interface-endpoint.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/live-sync-work/2017-03-09-profile/docs-ref-autogen/network/interface-endpoint.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/network/interface-endpoint?view=azure-cli-2017-03-09-profile&branch=pr-en-us-33) (azure-cli-2017-03-09-profile) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C11%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810110712015204-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rEiUQBtmRtTsco4jM3A1jbPZqQUNUgxhBUVfgbYWBls%3D&st=2018-10-11T07%3A11%3A00Z&se=2018-11-11T07%3A16%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
