### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\vjvc-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711102308574909-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kYNLlNiTOvh%2FtOdxY3hgy18wOaZzHEiepuxLryqc5Tg%3D&st=2017-11-10T23%3A04%3A12Z&se=2017-12-11T23%3A09%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\h2vm-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C14%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711142308131906-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aPjVC8SMRTBDQTbDkNJ5NWZM1jQFcHPMUseAZeeq0w4%3D&st=2017-11-14T23%3A03%3A55Z&se=2017-12-15T23%3A08%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ne4d-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C15%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711152311248917-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RIchjDLKENkbayRn6M7e7Xb9xmpL5DZYbmbB6yNoW2c%3D&st=2017-11-15T23%3A06%3A39Z&se=2017-12-16T23%3A11%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\nld0-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711172323441646-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XJqGyUP6Hw2j0zYxDgsaMo06%2Bja%2FSlUJH7mtqPimQBY%3D&st=2017-11-17T23%3A19%3A17Z&se=2017-12-18T23%3A24%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\gjhu-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C20%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711202307589163-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BbQgMwdKTAf%2BlaOj8zlgc5RbqMJZDedCX7ISyUGZc8Q%3D&st=2017-11-20T23%3A05%3A49Z&se=2017-12-21T23%3A10%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\skti-s, target branch: live, target branch commit: 16af471a30b5974efb7db7cbfb59f99b8b420ac8, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C11%5C28%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201711282255104893-19%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iPhIgbJY%2B%2B87oyJR9piZ4TtvXOsQLdEGXbwWU1fJyUw%3D&st=2017-11-28T22%3A51%3A00Z&se=2017-12-29T22%3A56%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
