### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pssy-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805222206237743-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VA5v%2Bu2fYvbJz3Q2B%2FfMcgfUc5mgmyFfQn9bftqLSxY%3D&st=2018-05-22T22%3A01%3A40Z&se=2018-06-22T22%3A06%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\bvuz-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805232228233340-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HAfF01PiNOjAWvOV0WOSmMW2O2B5bctNTGt55jIsqjo%3D&st=2018-05-23T22%3A23%3A39Z&se=2018-06-23T22%3A28%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ays0-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805232301406337-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oU47L3mdAhrSTFzrgY3GWkXaVSbg6MurckbYUHP1144%3D&st=2018-05-23T22%3A56%3A58Z&se=2018-06-23T23%3A01%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\by54-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C24%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805242231048011-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qmr2lJ29ddYxRQx0N8ajb8FtIqNyDuu0ZoxkSFx6EAg%3D&st=2018-05-24T22%3A26%3A20Z&se=2018-06-24T22%3A31%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\osz1-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C25%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805252208282206-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mxwTt8ZZ0FYqSt7FTuPglcVASnHhds9g5v3GE1baISg%3D&st=2018-05-25T22%3A03%3A44Z&se=2018-06-25T22%3A08%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\f0lc-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C29%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805292207367968-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=F4IghS6sKMf8xTHEyBxXuF%2FTLTstDrrc2u4BdctDpBU%3D&st=2018-05-29T22%3A02%3A55Z&se=2018-06-29T22%3A07%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\0num-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C30%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805302209272475-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=06aKZGsuXZeQ7B80nBB8Fz5GD%2BKuVfIMhTAZ4IrMuRI%3D&st=2018-05-30T22%3A04%3A44Z&se=2018-06-30T22%3A09%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\az2o-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C5%5C31%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201805312321290707-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eRV7LMRFucVtiQdPcw1iV9m5ySiycN9%2Bz3dyNUT%2FWuI%3D&st=2018-05-31T23%3A16%3A47Z&se=2018-07-01T23%3A21%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ijyh-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C1%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806011742226795-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2Bg4hREAXr54EIave19bZIgEsTQmrHX9S8yLJgBoWiqU%3D&st=2018-06-01T17%3A37%3A40Z&se=2018-07-02T17%3A42%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\5pze-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C4%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806042211248297-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qTs7%2FNhZPLbE3YFVB2yi5bgML8qfRAXt0e1JmzgYa7Q%3D&st=2018-06-04T22%3A06%3A42Z&se=2018-07-05T22%3A11%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\dh11-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C4%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806042304352644-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=b0%2Fa265MDJHXJFwhCQStGlo7J4gkX6t2shLHmWlkMaM%3D&st=2018-06-04T22%3A59%3A53Z&se=2018-07-05T23%3A04%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\yagv-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806050001039755-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2Brmf%2F79b4EwtIMsFKFE2K6liUJHagN0NHVnDmTKxSHk%3D&st=2018-06-04T23%3A56%3A29Z&se=2018-07-06T00%3A01%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\p3mo-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806050013564497-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lw42y5a1zL5YTexLMcVPvsez5ARvCpzQV50lpZPLZNA%3D&st=2018-06-05T00%3A09%3A16Z&se=2018-07-06T00%3A14%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\5b0l-s, target branch: live, target branch commit: 9911fa058524f1557c73558bb2879cffe3b045a7, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C6%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201806052208429443-31%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zhH%2BKhQowJgKr0jVDnaQBE5MA2AKPxuiYiGSJP19%2Feo%3D&st=2018-06-05T22%3A04%3A02Z&se=2018-07-06T22%3A09%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
