### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\vf5v-s, target branch: live, target branch commit: 88e076bddc94f9dd6c3b4e1a7092a5719ff9138f, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C4%5C12%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201804121727449025-28%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d3pivszo78mV9Z6eUajudA6rkWYyjsnNbdpa%2FX4VgOA%3D&st=2018-04-12T17%3A23%3A01Z&se=2018-05-13T17%3A28%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\eryo-s, target branch: live, target branch commit: 88e076bddc94f9dd6c3b4e1a7092a5719ff9138f, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C4%5C18%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201804182204259741-28%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FGPK1qmHfg0cvW5BSYcx70xnQDNaderG5X%2FVHziBWng%3D&st=2018-04-18T21%3A59%3A42Z&se=2018-05-19T22%3A04%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\3dvh-s, target branch: live, target branch commit: 88e076bddc94f9dd6c3b4e1a7092a5719ff9138f, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C4%5C19%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201804192217007669-28%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=E7m6w3W%2FoRpvSK5RBCqtzTJD98UJDUH8dufJCXBgANw%3D&st=2018-04-19T22%3A12%3A17Z&se=2018-05-20T22%3A17%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\kzmq-s, target branch: live, target branch commit: 88e076bddc94f9dd6c3b4e1a7092a5719ff9138f, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C4%5C20%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201804202206112708-28%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=o86sMm5Ah0jUo1IbbcmDEJmPdUzydiW43cfy9oYdyLI%3D&st=2018-04-20T22%3A01%3A28Z&se=2018-05-21T22%3A06%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
