### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Full build**: the average full build time is _10 min(s) 20 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Full build**: the average full build time is _10 min(s) 20 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-latest&branch=pr-en-us-1019) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1019) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-1019) (azure-cli-2018-03-01-hybrid) | [Details](#user-content-77c1685d-5aaf1b4e)

<a id="77c1685d-5aaf1b4e"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning]** `````Missing attribute: title. `````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning]** `````Missing attribute: title. `````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning]** `````Missing attribute: title. `````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C7%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C202005070959001879-1019%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nMkcl0L75kOdeyX63HX0nFIXlPSKF5%2FOOPxnxYg4apA%3D&st=2020-05-07T10%3A45%3A38Z&se=2020-06-07T10%3A50%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Pending**: waiting for processors ([8](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Full build**: the average full build time is _9 min(s) 45 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Full build**: the average full build time is _9 min(s) 45 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

:clock10: **Full build**: the average full build time is _9 min(s) 45 sec(s)_, this is based on the last _30_ build(s) for this repository.

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[94ed27c](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/94ed27ceaa214a039304f3cc04779cba09beea5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-latest&branch=pr-en-us-1019) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1019) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-1019) (azure-cli-2018-03-01-hybrid) | [Details](#user-content-77c1685d-e23bddf4)

<a id="77c1685d-e23bddf4"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **[Warning-InvalidMetadata]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing attribute: title. `````
 - **[Warning-InvalidMetadata]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing attribute: title. `````
 - **[Warning-InvalidMetadata]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=master)]** `````Missing attribute: title. `````
 - **[Warning-W.UndefinedValue]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning-W.UndefinedValue]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning-W.UndefinedValue]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 8**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 9**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C202005220114409583-1019%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RSLVrZqi4S0oBdIIClQ0Uq%2BraQFhHFWvM0oGSXfMv5w%3D&st=2020-05-22T01%3A54%3A00Z&se=2020-06-22T01%3A59%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/195583c8-b16e-8120-c0f7-89fb2f60ce66?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
