### PR TITLE
update

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-5) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/addfile?branch=pr-en-us-5) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705020740193480-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-5) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/addfile?branch=pr-en-us-5) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C3%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705030528210552-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-5) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/addfile?branch=pr-en-us-5) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C3%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705030528307302-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-5) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/addfile?branch=pr-en-us-5) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C3%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705030540376798-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Micosnow** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-5) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/addfile?branch=pr-en-us-5) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).
 - **Line 9**: **[Warning]** The content part of NOTE/WARNING/CAUTION/IMPORTANT/NEXT syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705220224136701-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\veie-s, target branch: master, target branch commit: 869e1ab4ab6950464cd7d9b134128c3049dab251, source branch: prtest, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C5%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201705220231325003-5%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
