### PR TITLE
Don't Merge! PR real time test for source branch full build

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by v-susu** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

:clock10: **Full build**: average full build time is _6 min(s) 20 sec(s)_ [calculated from last _28_ build(s)]

> Note: This is a FULL build due to a configuration change (usually in openpublishing.publish.config.json and/or docfx.json). It is strongly suggested to merge this configuration change after the business hours, as it could impact the overall build performance of other PRs on the 'pr-basebranch' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/pr-sourcefullbuild/docfx.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C3%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201903031346100666-55%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1%2F2oR8UkGP%2FP2ZIThjp7Yuncy2PfyUKnfRpZfHi%2Bw%2B8%3D&st=2019-03-03T13%3A49%3A07Z&se=2019-04-03T13%3A54%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

:clock10: **Full build**: average full build time is _6 min(s) 16 sec(s)_ [calculated from last _92_ build(s)]

> Note: This is a FULL build due to a configuration change (usually in .openpublishing.publish.config.json and/or docfx.json). It is strongly suggested to merge this configuration change after the business hours, as it could impact the overall build performance of other PRs on the 'pr-basebranch' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/pr-sourcefullbuild/docfx.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201903050113264309-55%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=baWh5pb1JziHKZPwnsUC9SPlZHLuERUfJ4FzTUWziFU%3D&st=2019-03-05T01%3A16%3A00Z&se=2019-04-05T01%3A21%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

:clock10: **Full build**: average full build time is _6 min(s) 16 sec(s)_ [calculated from last _93_ build(s)]

> Note: This is a FULL build due to a configuration change (usually in .openpublishing.publish.config.json and/or docfx.json). It is strongly suggested to merge this configuration change after the business hours, as it could impact the overall build performance of other PRs on the 'pr-basebranch' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by v-susu** [comment]
OPS Build status updates of commit _[04eb363](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/pull/55/commits/04eb363220a44e0e68ecaa7781c7ff944d789bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docfx.json](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/pr-sourcefullbuild/docfx.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C5%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201903050121123593-55%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ziv4w8zxwM0C337usO%2BaJzbAE1Z1XnhxOALPvmht810%3D&st=2019-03-05T01%3A23%3A01Z&se=2019-04-05T01%3A28%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
