### PR TITLE
Resolve syncing conflicts from live-sync-work to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from live-sync-work to live.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\5c5k-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C12%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801122314328164-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RE9Ov1yUyztAo2tgdO%2FEY8CJTmILzJeSzcFVo4tRl7g%3D&st=2018-01-12T23%3A09%3A48Z&se=2018-02-12T23%3A14%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\020y-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C18%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801182311060135-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rDM246t%2BNUE643vJzJS%2F1wodCpy25nh9ShSdNg6NlCI%3D&st=2018-01-18T23%3A06%3A40Z&se=2018-02-18T23%3A11%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\kohi-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C19%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801192323071295-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D%2BDy0yezWCDB7EH3qOqQwxfPo6tONNFjBU0XrENsOWI%3D&st=2018-01-19T23%3A18%3A22Z&se=2018-02-19T23%3A23%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\2qkv-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801222306569595-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hYnslkLDmBpi9y5FaLZOZSlz36WsmD9RXnpC0TTdyCw%3D&st=2018-01-22T23%3A02%3A13Z&se=2018-02-22T23%3A07%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\bdsa-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801232313317881-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=b%2BxF1Mx1jHUcpqstdIhM0sSSY2%2F0Jo4frBYaNKvXszc%3D&st=2018-01-23T23%3A08%3A49Z&se=2018-02-23T23%3A13%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\0qih-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C24%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801242307405487-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hD27OwbH%2Bu3t28aZatkviGu%2BUWxWP%2B2fHlwMC%2F7jFfc%3D&st=2018-01-24T23%3A02%3A55Z&se=2018-02-24T23%3A07%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\y25t-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C25%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801252306246522-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aD%2Bgt%2Bm9HR8nfP2R9rnyWENQMPr081H9YOuggjyg2v8%3D&st=2018-01-25T23%3A01%3A39Z&se=2018-02-25T23%3A06%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\gtqs-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C26%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801262307559868-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wUMS2RMXCqKo3Tj2dZhL2oX%2FBA5vKopU2T7G7bxCXII%3D&st=2018-01-26T23%3A03%3A26Z&se=2018-02-26T23%3A08%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\n0vf-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C29%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801292309211739-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LVLytQ7LFTsx%2BufH%2F%2BYfOVeLqmu%2Bptc8jTKuanKK38s%3D&st=2018-01-29T23%3A04%3A38Z&se=2018-03-01T23%3A09%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ao4k-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C1%5C30%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201801302304267050-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9DpV3uxK5eude3y5r4xLD96Udz1RyQ26B2evLmR0tLs%3D&st=2018-01-30T22%3A59%3A41Z&se=2018-03-02T23%3A04%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\1fu0-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C1%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802012307351390-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IB9XUPByikXZ8EIRFqqFvWXBDJ%2FLydfnibgs6inUxyA%3D&st=2018-02-01T23%3A02%3A51Z&se=2018-03-04T23%3A07%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\br1y-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802022305230833-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=76hcJKZrXxJATCWMj%2FxhfPwb4Ty6iosib6gRtazROSs%3D&st=2018-02-02T23%3A00%3A37Z&se=2018-03-05T23%3A05%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\5aeg-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C6%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802060043314762-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=z%2FnxjYakdueyUcZD24lwzf%2Bd3jD33ujdadVLYTY9LNE%3D&st=2018-02-06T01%3A30%3A20Z&se=2018-03-09T01%3A35%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\qogw-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C6%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802062310293814-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=o53IeIopSGuPwo5n5sHLUPM2Qj5%2BMIuqshC0pdhXrv4%3D&st=2018-02-06T23%3A05%3A44Z&se=2018-03-09T23%3A10%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\hkcb-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C7%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802072307158496-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=meTKdS4kjEJO9MhqeBRbOQEWn3hlhmqZMOpVp8%2Fps3A%3D&st=2018-02-07T23%3A02%3A32Z&se=2018-03-10T23%3A07%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pywy-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C8%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802082313120609-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Be1KTg5J0c6OnLS74rVtHgix8IU4WWSGtoKtuWOj13M%3D&st=2018-02-08T23%3A08%3A28Z&se=2018-03-11T23%3A13%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\0udr-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802100638188455-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WpTloQIGRk4gz4PA6pMNZ%2Buyixtlw1VgLMo6qwdqaTA%3D&st=2018-02-10T06%3A33%3A35Z&se=2018-03-13T06%3A38%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\2shk-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C13%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802130006584751-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lYr%2BYmdnwGEoctmM11Bn0%2FCeAx70lhBK9WzxIEJuxsg%3D&st=2018-02-13T00%3A02%3A17Z&se=2018-03-16T00%3A07%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\xsdn-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C13%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802132304190488-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xVhjTS8t7VNmAyEr2hC%2BbS0dfL86ekLd2IMCG59ddDc%3D&st=2018-02-13T22%3A59%3A34Z&se=2018-03-16T23%3A04%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\m2vw-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C14%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802142322583686-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gurziHgKceWkCp8jsq2hQF6x6C%2Fj2enqTMkA30lImO8%3D&st=2018-02-14T23%3A18%3A15Z&se=2018-03-17T23%3A23%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\q3he-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C15%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802152327002285-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tXNs5GqgGX1eQekxkI6VSM9plQZKxBj4Mx6ck2xecmA%3D&st=2018-02-15T23%3A22%3A16Z&se=2018-03-18T23%3A27%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\pq45-s, target branch: live, target branch commit: d493bfb9b0dd953133b144aa4a548a1e1d6bd876, source branch: live-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C2%5C16%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201802162319452604-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ijGcSLzTUXMyBUyLQChD12OacWMStJuNqAlAcfTO8yI%3D&st=2018-02-16T23%3A15%3A04Z&se=2018-03-19T23%3A20%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
