### PR TITLE
Don't Merge! Regression pull request test

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 59 sec(s)_, this is based on the last _599_ build(s) for this repository.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-latest&branch=pr-en-us-393) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2017-03-09-profile&branch=pr-en-us-393) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-393) (azure-cli-2018-03-01-hybrid) | [Details](#user-content-77c1685d-01ae197f) |

<a id="77c1685d-01ae197f"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C1%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908010335129496-393%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IWIXOJFG41rm1I5ncKYFrqnEr5kedLot8g9i3N7Emos%3D&st=2019-08-01T04%3A01%3A35Z&se=2019-09-01T04%3A06%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 59 sec(s)_, this is based on the last _604_ build(s) for this repository.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-latest&branch=pr-en-us-393) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2017-03-09-profile&branch=pr-en-us-393) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-393) (azure-cli-2018-03-01-hybrid) | [Details](#user-content-77c1685d-2b17ad5b) |

<a id="77c1685d-2b17ad5b"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: either ms.prod or ms.service is required. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908020430103030-393%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0n4%2Fd9Ufl%2BEO2lpNiTJU2Mm34xAmHEF4CSsTxl72nWY%3D&st=2019-08-02T04%3A33%3A46Z&se=2019-09-02T04%3A38%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 59 sec(s)_, this is based on the last _605_ build(s) for this repository.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[35fb1e9](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/35fb1e944b2f11606cafe0c51e97ee1c8fc80883)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-latest&branch=pr-en-us-393) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2017-03-09-profile&branch=pr-en-us-393) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-393) (azure-cli-2018-03-01-hybrid) | [Details](#user-content-77c1685d-7b8cb874) |

<a id="77c1685d-7b8cb874"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 7**: **[Warning]** `````Invalid file link:(~/nonexisted1.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/nonexisted2.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/nonexisted3.md).`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C2%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908020612012659-393%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i5zOsdeHO2s8ehEkBYA312f7JCC0FTbAhcnnoRnGl4s%3D&st=2019-08-02T06%3A15%3A11Z&se=2019-09-02T06%3A20%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
