### PR TITLE
Prtest

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-12) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/newfiletest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/newfiletest.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/newfiletest?branch=pr-en-us-12) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708170234044661-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-12) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/newfiletest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/newfiletest.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/newfiletest?branch=pr-en-us-12) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708170301285908-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-12) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/newfiletest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/newfiletest.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/newfiletest?branch=pr-en-us-12) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708170601326697-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/testingpullrequest?branch=pr-en-us-12) | [Details](#user-content-docs-ref-conceptual%2FTestingPullRequest.md)
[docs-ref-conceptual/newfiletest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/newfiletest.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/newfiletest?branch=pr-en-us-12) |

<a name="docs-ref-conceptual%2FTestingPullRequest.md"></a>
### [docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md)
 - **Line 4**: **[Warning]** Invalid file link:(~/nonexisted1.md).
 - **Line 5**: **[Warning]** Invalid file link:(~/nonexisted2.md).
 - **Line 6**: **[Warning]** Invalid file link:(~/nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708170609534834-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/TestingPullRequest.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/addFile.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/addFile.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/newfiletest.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest/docs-ref-conceptual/newfiletest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708171043212805-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch prtest has been deleted or has been force pushed: fatal: Could not parse object &#39;2631ee73846a264b8b40260e85865d0a5432990a&#39;.


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C8%5C17%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201708171044162323-12%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
