### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\a0cx-s, target branch: master, target branch commit: 9901517d6151375d55d369498cfe85bed82682f2, source branch: master-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C9%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810092134364159-32%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uIflmm7VsSTATobcOx4kHHLJu7mQgozNsRPqlngpx90%3D&st=2018-10-09T21%3A29%3A52Z&se=2018-11-09T21%3A34%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\gulj-s, target branch: master, target branch commit: 9901517d6151375d55d369498cfe85bed82682f2, source branch: master-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C9%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810092200567159-32%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xU07oF8R0Cu%2BJd%2BXMRmj6cjlJNVyvWmezQcHuHPFUKU%3D&st=2018-10-09T21%3A56%3A12Z&se=2018-11-09T22%3A01%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\jjfa-s, target branch: master, target branch commit: 9901517d6151375d55d369498cfe85bed82682f2, source branch: master-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810100029536648-32%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=y%2BgrUqokqxtB%2BhWwYFvX9O%2BXkgzw8tyEQrQAv5A9u1A%3D&st=2018-10-10T00%3A25%3A09Z&se=2018-11-10T00%3A30%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/azure-docs-cli-python, working directory: W:\ubwf-s, target branch: master, target branch commit: 9901517d6151375d55d369498cfe85bed82682f2, source branch: master-sync-work, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C10%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810101658391323-32%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dH36eQ3cAcFLSOOqjfRAcigqZP1C3dc3dmawP9ScIJ0%3D&st=2018-10-10T16%3A53%3A54Z&se=2018-11-10T16%3A58%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.gitattributes](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/master-sync-work/.gitattributes) | :white_check_mark:Succeeded | |
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/ext/dms-preview/dms/project/task.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ext/dms-preview/dms/project/task.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ext/dms-preview/dms/project/task?view=azure-cli-2017-03-09-profile&branch=pr-en-us-32) (azure-cli-2017-03-09-profile) |
[2018-03-01-hybrid/docs-ref-autogen/ext/dms-preview/dms/project/task.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/master-sync-work/2018-03-01-hybrid/docs-ref-autogen/ext/dms-preview/dms/project/task.yml) | :white_check_mark:Succeeded | |
[latest/docs-ref-autogen/ext/dms-preview/dms/project/task.yml](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/master-sync-work/latest/docs-ref-autogen/ext/dms-preview/dms/project/task.yml) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/ext/dms-preview/dms/project/task?view=azure-cli-latest&branch=pr-en-us-32) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C10%5C11%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201810110715508216-32%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R5FG6QYbCH0Yk5TLntJzRRvJdlc83egaB7vVnCUGVi0%3D&st=2018-10-11T07%3A14%3A45Z&se=2018-11-11T07%3A19%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
