### PR TITLE
pr test without metavalidation

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-b68a88c2) |

<a id="b68a88c2"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C22%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908220936361881-470%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WS7kfMiA9scBs202ZXvFhOLZUdRPdsI1yFoJ77iQqwk%3D&st=2019-08-22T09%3A31%3A57Z&se=2019-09-22T09%3A36%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 56 sec(s)_, this is based on the last _702_ build(s) for this repository.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/azure-cli-extension-alias.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest-nometavalidation/docs-ref-conceptual/azure-cli-extension-alias.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-latest&branch=pr-en-us-470) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2017-03-09-profile&branch=pr-en-us-470) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-470) (azure-cli-2018-03-01-hybrid) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908230119513902-470%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1uce3dbmPr3UuVLxdzKC91U5TSjrkvO9r6cpYhfyH3I%3D&st=2019-08-23T01%3A22%3A58Z&se=2019-09-23T01%3A27%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 56 sec(s)_, this is based on the last _703_ build(s) for this repository.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/azure-cli-extension-alias.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest-nometavalidation/docs-ref-conceptual/azure-cli-extension-alias.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-latest&branch=pr-en-us-470) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2017-03-09-profile&branch=pr-en-us-470) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-470) (azure-cli-2018-03-01-hybrid) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908230500596120-470%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dbfclVhfqcHKR6JPJE4cs%2FePJd2PQWYBSOo5Z54tjWM%3D&st=2019-08-23T05%3A04%3A10Z&se=2019-09-23T05%3A09%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

:clock10: **Full build**: the average full build time is _5 min(s) 56 sec(s)_, this is based on the last _704_ build(s) for this repository.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[078701f](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/commits/078701f35924592a8e3399f15b5b763e27a0df6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[docs-ref-conceptual/azure-cli-extension-alias.md](https://github.com/OPS-E2E-PPE/azure-docs-cli-python/blob/prtest-nometavalidation/docs-ref-conceptual/azure-cli-extension-alias.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-latest&branch=pr-en-us-470) (azure-cli-latest)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2017-03-09-profile&branch=pr-en-us-470) (azure-cli-2017-03-09-profile)<br/> [View](https://ppe.docs.microsoft.com/en-us/e2eppe-azure-cli-docs/azure-cli-extension-alias?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-470) (azure-cli-2018-03-01-hybrid) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C23%5C195583c8-b16e-8120-c0f7-89fb2f60ce66%5CPullRequest%5C201908231031596758-470%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=686XaOctK16jR%2FOcukBBgR5M0Mf8eBoFpFs6aIqZDf8%3D&st=2019-08-23T10%3A35%3A04Z&se=2019-09-23T10%3A40%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
